[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# The @netlify/plugin-nextjs handles API routes automatically.
# We only need the fallback for client-side routing.

# Fallback for client-side routing (e.g., for SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false