[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Handle Next.js API routes, including auth callbacks
[[redirects]]
  from = "/api/auth/callback/*"
  to = "/.netlify/functions/next_api_auth_callback_:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/auth/*"
  to = "/api/auth/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# Fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false